export const nigerianStates = [
  { code: "abia", name: "Abia" },
  { code: "adamawa", name: "Adamawa" },
  { code: "akwaIbom", name: "Akwa Ibom" },
  { code: "anambra", name: "Anambra" },
  { code: "bauchi", name: "Bauchi" },
  { code: "bayelsa", name: "Bayelsa" },
  { code: "benue", name: "Benue" },
  { code: "borno", name: "Borno" },
  { code: "crossRiver", name: "Cross River" },
  { code: "delta", name: "Delta" },
  { code: "ebonyi", name: "Ebonyi" },
  { code: "edo", name: "Edo" },
  { code: "ekiti", name: "Ekiti" },
  { code: "enugu", name: "Enugu" },
  { code: "abuja", name: "FCT - Abuja" },
  { code: "gombe", name: "Gombe" },
  { code: "imo", name: "Imo" },
  { code: "jigawa", name: "Jigawa" },
  { code: "kaduna", name: "Kaduna" },
  { code: "kano", name: "Kano" },
  { code: "katsina", name: "Katsina" },
  { code: "kebbi", name: "Kebbi" },
  { code: "kogi", name: "Kogi" },
  { code: "kwara", name: "Kwara" },
  { code: "lagos", name: "Lagos" },
  { code: "nasarawa", name: "Nasarawa" },
  { code: "niger", name: "Niger" },
  { code: "ogun", name: "Ogun" },
  { code: "ondo", name: "Ondo" },
  { code: "osun", name: "Osun" },
  { code: "oyo", name: "Oyo" },
  { code: "plateau", name: "Plateau" },
  { code: "rivers", name: "Rivers" },
  { code: "sokoto", name: "Sokoto" },
  { code: "taraba", name: "Taraba" },
  { code: "yobe", name: "Yobe" },
  { code: "zamfara", name: "Zamfara" },
];
